server:
  port: 9000
spring:
  data:
    mongodb:
      database: kotlin-graphql
      port: 27017
      authentication-database: admin
      username: ${MONGO_USER_ADMIN}
      password: ${MONGO_PASS_ADMIN}
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11
